name: NodeJS HelloWorld App
run-name : ${{ github.workflow }}

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: Checkout Repository
        uses: actions/ckeckout@4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20.0"

      - name: Install Dependencies
        run: |
          cd nodejs/hello 
          npm install
          npm install pm2 -g

      - name : Stop App with PM2
        run: |
          cd nodejs/hello
          pm2 start app.js --name "hello-app"
          pm2 save

      - name : Stop App with PM2
        run: |
          pm2 list
          pm2 stop "hello-app"
          pm2 delete "hello-app"